### ISSUE TITLE
Can you break abc using rainbow signature algorithm?

### ISSUE THREAD

**Issue by goodhearted** [WardBeullens/BreakingRainbow#1]
Can you break abc using rainbow signature algorithm? 
https://github.com/abcmint/abcmint

**Comment by WardBeullens** [comment]
Yes

**Comment by goodhearted** [comment]
On behalf of the anti-quantum cracking encryption currency ABC community, I officially invite you to crack abc. If you can crack it successfully, I think it will also have cross-generational significance in the history of cryptocurrency, and it will be recorded in history forever.
This will be the first time in history that the private key is obtained from the encrypted public key.
After your paper was published, it had a great impact on us, and we discussed it within our community. We thought,
1. We think that a notebook in your paper, cracking the signature of the rainbow algorithm NIST SL1@Round2 in one weekend is extremely lax and exaggerated, although you are one of the best cryptographers.
At present, the vast majority of cryptography circles recognize that rainbow signatures can be used in cryptocurrencies without problems.
2. At present, it is very difficult to crack in practice, and we have not seen a successful case. Taiwan and Germany have two Ph.D.s in mathematics and computer science who think that your algorithm is unlikely to be cracked by a rational Ph.D. in mathematics.
It takes a week or a month to adjust and perfect the program, and it will be possible to run through.
3. We also want to see whether it will happen for the first time in history to decrypt the public key of an encrypted currency to obtain the private key. We think that the public key of ABC is not easy to find. The public key of ABC uses the relocpubkey or paddingpubkey technology. .
4. We know that the LUOV algorithm of the University of Leuven has been cracked by Professor Ding, the inventor of the rainbow algorithm.
5. We can provide the address where the public key has been exposed. This is Jin Liu, the coin holding address of the chairman of the ABCMint Foundation, and we have been authorized.
(1).8JEj33ydPCSYhkaYv17PXfuPF66rtr6cTn8on5zWHNgPkoKpq
Related Information:
abcmint: http://www.abcmint.org/
github: https://github.com/abcmint/abcmint
Blockchain URL: https://abcscan.io/#/

**Comment by WardBeullens** [comment]
An implementation of the key recovery attack is publicly available. Anyone can verify that it runs sucsessfully for the parameter set currently used in abc. The Rainbow team (Jintai Ding) publicly confirmed: "We implemented and tested his attack and it works". https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/KFgw5_qCXiI/m/omEactzVAgAJ

If you have reasons to believe the attack doesn't work as claimed I would be happy to hear them. 

Despite your kind invitation, I will not spend my time stealing ABC.

**Comment by goodhearted** [comment]
I saw the link you sent, thank you for your reply, we still think you can't crack abc, because there is still a difference between theory and practice, now is an excellent opportunity to practice, we also hope that you can work with us together Participate in promoting the accelerated implementation of the PQC algorithm in the cryptocurrency field
1. We don't think this is theft, as long as you can show us the contents of the private key in the next part after cracking, we can confirm whether it is successful or not.
2. We think that your attack is too accidental and coincidental, and it can only be cracked within 53 hours if you are lucky
3. We believe that the vast majority of cryptography circles agree that rainbow signatures can be used in cryptocurrencies, so there are still people who disagree with your statement
4. We haven't seen the cracking event yet, and we are looking forward to it happening.
5. We also consulted some cryptography experts. Experts believe that it is necessary to be proficient in multi-variables at the same time, to understand the abc source code and your attack algorithm to crack, and to avoid mathematical bugs in your code, which is what we think Basically no one can crack, including you
Related Information:
abcmint: http://www.abcmint.org/
github: https://github.com/abcmint/abcmint
Blockchain URL: https://abcscan.io/#/

**Comment by WardBeullens** [comment]
https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/MYmlJkXQDRI/m/wKhZ-fuAAwAJ
